version: "3.9"

services:
  app:
    build:
      context: .
      target: runtime
    image: joyus:prod
    container_name: joyus_prod
    ports:
      - "10085:12345"
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgres://joyus:TW9uICAxIERlYyAx@db:5432/joyus
    depends_on:
      - db
    restart: always

  db:
    image: postgis/postgis:16-3.4
    container_name: joyus_postgis_prod
    environment:
      - POSTGRES_DB=joyus
      - POSTGRES_USER=joyus
      - POSTGRES_PASSWORD=TW9uICAxIERlYyAx

    volumes:
      - pgdata_prod:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata_prod:
